### ISSUE TITLE
Gazetteer review

### ISSUE THREAD

**Issue by itcareerswitch** [3782291211/majidLaklouk#1]
- [x] Add a pre-loader to hide the site until the first country has rendered
- [x] Add cURL/JSON error handling to PHP
- [x] Replace country select with standard select tag
- [x] Only authorised JSON file must be used - all other data must be sourced from APIs in real time
- [x] Display markers when country loads
- [x] Name marker groups in layers control: https://codepen.io/itcareerswitch/pen/MWBgjGy/b7a8809a112eb804fbb659952e2a19f2
- [x] Format all dates and numbers ([dateJS](https://github.com/datejs/Datejs) & [numeralJS](http://numeraljs.com/))
- [x] Modals with long running text should use "modal-dialog-scrollable" class. Many are too wide
- [x] Holidays - year in title and each data formatted as, for example 1st January
- [x] At a glance: https://codepen.io/itcareerswitch/pen/mdQxgRx/094165febdac816a99a162d754f5679d
- [x] Weather example: https://codepen.io/itcareerswitch/pen/vYzEBvX/58fd2357741ed73196232e5d295850e8
- [x] News example: https://codepen.io/itcareerswitch/pen/OJaypBQ/01f42a51bbea244d756dcbaf9496c1e5
- [x] Currency example: https://codepen.io/itcareerswitch/pen/dygBBam/a9c69b65f132c1f17c2552e72a244238
- [x] Clear console of all logs and errors

**Comment by 3782291211** [comment]
All changes/corrections have been completed.

**Comment by 3782291211** [comment]
All changes/corrections have been completed.
