### ISSUE TITLE
Company Directory review

### ISSUE THREAD

**Issue by itcareerswitch** [3782291211/majidLaklouk#2]
- [x] Favicon
- [x] Filter on department OR location
- [x] All selects must be ordered alphabetically
- [x] Add modal forms are not compliant - use "form-floating" buttons should be "SAVE" and "CANCEL"
- [x] show.bs.modal events for all modals to populate controls and/or rebuild selects from query to database (except add location)
- [x] All modals must open vertically centred, without backdrop, with shadow and upper case text in buttons
- [x] Deletion confirmations must make AJAX call to retrieve name of entry and display it
- [x] Check for dependencies: https://codepen.io/itcareerswitch/pen/bGZrrxK/c9ce3c5ffddf93d2d6ea89676d17cdd1
- [x] Never use "*" in a SQL query - always name the columns even if it is all of them
- [x] Do not use CDNs

**Comment by 3782291211** [comment]
All changes/corrections have been completed.
